### ISSUE TITLE
Maybe a stupid question?

### ISSUE THREAD

**Issue by Arkkimaagi** [davatron5000/fit-vids#2]
Why not use `style="--aspect: 16/9;` or even `style="--aspect: 320/180;` (or just the px size) and `aspect-ratio: var(--aspect, 16/9)` with the css from blogpost instead of this js?

**Comment by davatron5000** [comment]
Absolutely do that!  CSS is really powerful. If you find a workaround where you don’t need this don’t use it. 

This is more for the use case where your CMS or being lazy doesn’t allow for that.
