### ISSUE TITLE
Remove the constructor

### ISSUE THREAD

**Issue by Danny-Engelman** [davatron5000/fit-vids#3]
Doesn't a class without a ``constructor`` calls its parent class constructor  by default?

**Comment by jens-struct** [comment]
I was also wondering about this, as I'm currently looking at the source of some light dom custom elements, to get inspiration. @davatron5000 Do you know something, we don't?

Thanks for your input here!

**Comment by davatron5000** [comment]
Yep. Don't need it. Removed!
