### ISSUE TITLE
Gzip crazyness

### ISSUE THREAD

**Issue by Danny-Engelman** [davatron5000/fit-vids#4]
disclaimer: I have this thing with GZIP; forever want to squeeze out the next byte

You say 419 Bytes

* skip all the edge case tests
* No need to define ``FitVids`` as a class, since we only use it once. No need to export it either
* Lets abuse the non-existing ``connectedCallback`` **parameters** and define our ``s`` **variable** there
* Why create an Array with2 **strings** and then ``join(",")`` it to create **one** string.
* But isn't the default for ``height`` **auto** anyway, so why set it? https://developer.mozilla.org/en-US/docs/Web/CSS/height
* ``.map`` is 4 bytes shorter and just as fast unless your name is Max Verstappen
* Template Literals suck up bytes, and CPU cycles 

````javascript
  customElements.define("fit-vids", class extends HTMLElement {
    connectedCallback(s = 'iframe[src*="youtube"], iframe[src*="vimeo"]') {
      this.style.display = "block";
      this.querySelectorAll(s).map(v => {
        v.style.width = "100%";
        v.style.maxWidth = "100%";
        v.style.aspectRatio = v.getAttribute("width") + "/" + v.getAttribute("height");
        v.removeAttribute("height");
        v.removeAttribute("width");
      });
    }
  });
````

**367** Bytes Minified

**246** Bytes Gzipped

**Comment by davatron5000** [comment]
Very cool. I'm going to pass because golfing the code down isn't my top priority. I want to maintain readability. 

Nice point on `height: auto`. I initially had it to override the `[height]` attribute... but since I'm removing the `[height]` attribute I maybe don't need that.
